### PR TITLE
Update main.js DOM text reinterpreted as HTML

### PR DESCRIPTION
**Pull request by Shivam7-1**
By using innerText, it will avoid the risk of HTML injection, as these properties automatically escape any HTML special characters in the provided text. This helps prevent cross-site scripting (XSS) vulnerabilities by treating the input as plain text rather than interpreted HTML

### CODE REVIEW

**Comment by Shivam7-1** [comment]
Hi @Snugug Could You Please Review This PR 
Thanks

**Comment by Shivam7-1** [comment]
Hi @Snugug Could You Please Review This PR
Thanks

**Comment by Shivam7-1** [comment]
Hi @Snugug 
Thanks For Reviewing PR
I think Above PR Would Be Useful as Here in code is in Comment Form ?

Thanks

**Comment by Snugug** [comment]
Like I said in my other PR review, this doesn't pose an XSS concern because no untrusted data is being injected, it's being set to a trusted empty string. It doesn't matter in what section of code it's in, per se, but rather what the code is doing.

**Pull request closed without merging**
